// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package mysql

import (
	"database/sql"

	types "github.com/laeni/pri-dns/types"
)

// 解析记录表.
type Domain struct {
	ID int64
	// 客户端地址（生效范围）。<br />如果全局生效，则该字段为空。
	Host string
	// 主机记录。由于可能存在泛域名，所以为了便于使用索引，存储时将采用反转格式，如：example.com
	Name string
	// 记录值
	Value sql.NullString
	// TTL
	Ttl sql.NullInt32
	// 状态。<br />ENABLE-启用
	Status string
	// 记录类型。带"NO_"前缀的表示用于禁用全局解析。<br />A / NO_ALL / NO_A
	Type sql.NullString
	// 优先级。值越小优先级越高。
	Priority int32
	// 创建时间
	CreateTime types.LocalTime
	// 修改时间
	UpdateTime types.LocalTime
}

// 转发配置.
type Forward struct {
	ID int64
	// 创建时间
	CreateTime types.LocalTime
	// 修改时间
	UpdateTime types.LocalTime
	// 需要转发解析的域名
	Name string
	// 转发目标DNS服务器，可以是多个，多个以逗号分割
	Dns string
	// 生效范围。可选值：全局或某个具体Ip(如果为空则表示全局)
	Bind sql.NullString
	// 是否启用
	Enabled string
	// 该域名对应的解析历史。可能需要导出使用
	History sql.NullString
}
