// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package mysql

import (
	"database/sql"

	types "github.com/laeni/pri-dns/types"
)

// 解析记录表.
type Domain struct {
	ID int64
	// 客户端地址（生效范围）。<br />如果全局生效，则该字段为空。
	ClientHost string
	// 主机记录。由于可能存在泛域名，所以为了便于使用索引，存储时将采用反转格式，如：example.com
	Name string
	// 记录值
	Value sql.NullString
	// TTL
	Ttl sql.NullInt32
	// 记录类型。<br />A | AAAA
	DnsType sql.NullString
	// 是否拒绝全局解析
	DenyGlobal string
	// 状态。<br />ENABLE-启用
	Status string
	// 创建时间
	CreateTime types.LocalTime
	// 修改时间
	UpdateTime types.LocalTime
}

// 转发配置.
type Forward struct {
	ID int64
	// 客户端地址（生效范围）。<br />如果全局生效，则该字段为空。
	ClientHost string
	// 需要转发解析的域名
	Name string
	// 转发目标DNS服务器，可以是多个，多个以逗号分割
	DnsSvr sql.NullString
	// 是否拒绝全局解析
	DenyGlobal string
	// 状态。<br />ENABLE-启用
	Status string
	// 创建时间
	CreateTime types.LocalTime
	// 修改时间
	UpdateTime types.LocalTime
}

// 解析历史.
type History struct {
	ID int64
	// 需要转发解析的域名
	Name string
	// 解析记录，用于导出使用，多个以逗号分割
	History sql.NullString
	// 创建时间
	CreateTime types.LocalTime
	// 修改时间
	UpdateTime types.LocalTime
}
